<div class="row">
    <div class="col-8 mb-3">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Procurar problemas" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-outline-primary" type="button">
                Pesquisar...
            </button>
        </div>
    </div>
    <div class="col-4">
        <a href="<?= route('demands.create') ?>" class="btn btn-outline-primary">
            <i class="fe fe-plus"></i>
            Registrar Problema
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Título</th>
        <th></th>
    </thead>
    <tbody>
        <?php foreach ($demands as $demand) : ?>
            <tr>
                <td><a href="<?= route('demands.show', ['id' => $demand->id]) ?>">#<?= $demand->id ?></a></td>
                <td><?= $demand->title ?></td>
                <td>
                    <div class="d-flex flex-row-reverse">
                        <form action="<?= route('demands.destroy', ['id' => $demand->id]) ?>" method="POST" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-link"><i class="bi bi-archive"></i></button>
                        </form>
                        <a href="<?= route('demands.edit', ['id' => $demand->id]) ?>" class="btn btn-link pe-0">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

