<div class="row">
    <div class="col-8 mb-3">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Procurar problemas" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-outline-primary" type="button">
                Pesquisar...
            </button>
        </div>
    </div>
    <div class="col-4">
        <a href="<?= route('demands.create') ?>" class="btn btn-outline-primary">
            <i class="fe fe-plus"></i>
            Registrar Problema
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Título</th>
        <th>Descrição</th>
        <th>Status</th>
        <th>Ações</th>
    </thead>
    <tbody>
    </tbody>
</table>

