<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rastreador de Problemas</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
  <!-- Adicione isso no <head> do seu HTML -->
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#demand_user_id').select2();
    });
  </script>

</head>

<body class="bg-light">
    <nav class="navbar fixed-top bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="<?= route('demands.index') ?>">Demandas</a>

            <?php if ($this->current_user) : ?>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white " data-bs-toggle="dropdown" href="#" aria-expanded="false">
                        <?= $this->current_user->email ?>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="<?= route('profile.show') ?>">Profile</a>
                        <a class="dropdown-item" href="<?= route('users.logout') ?>">Sair</a>
                    </div>
                </div>
            <?php endif; ?>

        </div>
    </nav>

    <main class="container col-8">
            <section class="row justify-content-md-center">

                <?php require '_flash_message.phtml'; ?>

                <header class="my-3 p-3 bg-white rounded">
                    <h3 class="text-primary">
                        <?= $title ?>
                    </h3>
                </header>

                <?php require $view ?>

            </section>
    </main>
</body>

</html>
